### ISSUE TITLE
ERROR in ./~/react-block-ui/style.css

### ISSUE THREAD

**Issue by hhh146578** [Availity/react-block-ui#10]
I just use react-block-ui in my react project.
First I run 
npm install --save react-block-ui react react-dom

And write something like
```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import ContentBody from './components/content_body';
import NavBar from './components/NavBar.js';
import Main from './components/Main.js';
import { BrowserRouter } from "react-router-dom";

import BlockUi from 'react-block-ui';
import 'react-block-ui/style.css';
import { Button } from 'react-bootstrap';



class App extends Component{
  constructor(props) {
    super(props);

    this.toggleBlocking = this.toggleBlocking.bind(this);
    this.state = {
      blocking: false,
    };
  }

	toggleBlocking() {
		this.setState({blocking: !this.state.blocking});
	}

	render(){
		return (
			<div>
				<BlockUi tag="div" blocking={this.state.blocking}>
			 	<NavBar />
				<Main />
				</BlockUi>
		        <Button onClick={this.toggleBlocking} color="primary">Toggle Block</Button>

			</div>
		);
	}
}

```

But I get the following error

```
ERROR in ./~/react-block-ui/style.css
Module parse failed: /home/hungwenc/1111-drones-map/node_modules/react-block-ui/style.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/hungwenc/1111-drones-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
 @ ./src/index.js 31:0-35
```

Is there any bug in the library?

**Comment by TheSharpieOne** [comment]
You will need a style loader and css loader for webpack to be able to import css like that. Docs for importing styles/css can be found at https://webpack.github.io/docs/stylesheets.html.

Alternatively, you can use `<link href="https://unpkg.com/react-block-ui@1.0.2/style.css">` in your html to pull the styles resource from a CDN. Using a CDN means you would not need to import the style in your code.

**Comment by TheSharpieOne** [comment]
@hhh146578 did the comment above address your issue?

**Comment by TheSharpieOne** [comment]
I'm closing this issue as it is inactive. If the issue is unresolved, please comment and I will reopen.

**Comment by gautambt** [comment]
I am getting the same error while trying to use react-block-ui with webpack on rails. I've tried to use style.min.js as recommended above with no luck (The minified file has the comment as well). The default webpack config for rails does come with style loader enabled by default. and I am able to import other css files fine. If I remove the comment "" from style.css everything works fine.

**Comment by TheSharpieOne** [comment]
There is not style.min.js just a style.css. If your webpack config is only looking for javascript files then you need to either adjust your configuration or include the styles from the cdn.
I would recommend also using create-react-app as it comes out of the box with css import capabilities.

**Comment by gautambt** [comment]
The issue is probably not with webpack config as I am able to load other css files from js files just fine. I am able to import and use the library fine if I remove the comment `<!-- CSS Animations -->` on line 51. The [syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Comments) for commenting in css files is  `/* Css Animations */`.

**Comment by TheSharpieOne** [comment]
I fixed that comment syntax and will release it when I get to a computer.

**Comment by TheSharpieOne** [comment]
@gautambt v1.1.1 has the fix. Please give it a try.
